### ISSUE TITLE
中断使用互拆锁问题

### ISSUE THREAD

**Issue by camel5** [illusionlee/bs8116a#1]
RtThread的I2C底层驱动使用了互拆锁，BS8116A按键在中断中断中读写。互拆锁是不允许在中断中使用，按键触发中断后，程序死在互拆锁的中断断言中。屏蔽后可以正常运行，目前I2C还有问题，怀疑继续调试中。例外源码编码是utf_8,建议注释改为英文，容易乱码。rtthread的{}都是换行的，建议代码风格保持一致。

**Comment by illusionlee** [comment]
感谢你的建议，中断中进行处理确实有问题。开发这个软件包时，没有经过严谨的设计，后续应该会优化，也欢迎你PR :)
关于代码风格，RTT对软件包的要求其实很松，我是按照自己舒服的风格来的;P
utf-8算是比较友好的编码了，中文注释也还好吧，降低英文不太好的入门者学习门槛。
再次感谢
