### ISSUE TITLE
请教个问题，关于 KEY12 和 KEY16 误触发

### ISSUE THREAD

**Issue by huqifj** [illusionlee/bs8116a#2]
我没有使用 IQR，使用了 16 个按键，其他按键都正常，除了 12 和 16。

现象是触摸 12 或 16 之后，读回来数据的 bit 11 和 bit 15 有时就一直为 1，不知道你们有没有遇到过这个问题，请教一下，谢谢！

**Comment by huqifj** [comment]
已解决，channel 16 PCB 布线问题

**Comment by illusionlee** [comment]
666
